# Description of what this change includes
# Revision number
# DateAWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: 
              !Sub "arn:aws:s3:::${S3Bucket}/*"

Outputs:
  WebsiteURL:
    Description: "URL for website hosted on S3"
    Value: !GetAtt S3Bucket.WebsiteURL

  S3BucketSecureURL:
    Description: "Secure domain name of the bucket"
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt S3Bucket.DomainName
